### ISSUE TITLE
`prettier-plugin-tailwindcss` is not added automatically

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/cli#821]
When the following commands are executed:

```shell
pnpm dlx sv create --template minimal --add eslint prettier tailwindcss="plugins:forms" --types jsdoc javascript
pnpm dlx sv create --template minimal --add eslint prettier tailwindcss="plugins:forms" --types ts typescript
```

- `eslint-config-prettier` and `prettier-plugin-tailwindcss` are not installed
- `pnpm format` does not seem to run after creation (or silently fails?)

For diff, see https://github.com/hyunbinseo/svelte-kit-templates/commit/d4c563a8fab4a2c531dc31b2c59e203b73ac68e5

Is this the desired action for `create --add` in one go? Or is it broken?

- https://github.com/sveltejs/cli/pull/756

**Comment by manuel3108** [comment]
It's definitely broken. Checking.

**Comment by manuel3108** [comment]
This should be fixed by #823. Can you confirm by running
```shell
pnpm dlx https://pkg.pr.new/sveltejs/cli/sv@823 #...
```

**Comment by hyunbinseo** [comment]
I still see a few errors when running this command:

```shell
pnpm dlx sv create --template minimal --add eslint prettier tailwindcss="plugins:forms" --types ts typescript
```

Seems like prettier format has not run after scaffolding?

1. `.prettierrc` is not formatted (plugins array should be a single line)
2. `eslint.config.js` does not seem to be formatted (comments, array)
3. `src/routes/+layout.svelte` has a leading whitespace in an empty line

https://github.com/hyunbinseo/svelte-kit-templates/commit/1662515970a2b3332ac50f5b735ce6f93b2ba072

**Comment by manuel3108** [comment]
You are missing the `--install pnpm` flag. But there is also a bug that needs to be fixed on our side. On it.

**Comment by hyunbinseo** [comment]
@manuel3108 Thanks for the solution.

It's now fixed in https://github.com/hyunbinseo/svelte-kit-templates/commit/ecc261a0f5b2e6ba8ce5e6e2146faf6867a65c7d

Since no add-on and no installation resulted in a formatted template, I was expecting the same in CLI.

```
┌  Welcome to the Svelte CLI! (v0.10.6)
│
◇  Where would you like your project to be created?
│  ./
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  none
│
◆  Project created
│
◇  Which package manager do you want to install dependencies with?
│  None
```
